name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest

    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Shravanimath

          # Pink theme
          background: "#0D1117"
          pacman_color: "#ff4da6"
          dot_color: "#ff99cc"
          wall_color: "#ff4da6"

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
